### ISSUE TITLE
Source hardware

### ISSUE THREAD

**Issue by NickHale1** [NickHale1/Deadbolt-Detector#1]
We need to get our hands on hardware for the project
- raspberry pi w/ wi-fi & bluetooth
- proximity sensor
- power supply
- case

**Comment by NickHale1** [comment]
Purchased a pi on amazon

**Comment by nearybatwit** [comment]
Identified power supply: <a href="https://www.amazon.com/Raspberry-Model-Official-SC0218-Accessory/dp/B07W8XHMJZ/ref=pd_day0fbt_img_sccl_1/147-6213389-1358511?pd_rd_w=SrwP6&pf_rd_p=bcb8482a-3db5-4b0b-9f15-b86e24acdb00&pf_rd_r=SXFGKQGJB1KVJWJCFASH&pd_rd_r=8956787e-8b82-4843-936a-3e8b0b8a6c3b&pd_rd_wg=0I3Kz&pd_rd_i=B07W8XHMJZ&th=1" rel="external">Power Supply</a>

Adequate Raspberry Pi Case: <a href="https://www.amazon.com/Miuzei-Raspberry-Aluminum-Included-Black/dp/B07VX3HQGJ/ref=pd_day0fbt_img_sccl_2/147-6213389-1358511?pd_rd_w=SrwP6&pf_rd_p=bcb8482a-3db5-4b0b-9f15-b86e24acdb00&pf_rd_r=SXFGKQGJB1KVJWJCFASH&pd_rd_r=8956787e-8b82-4843-936a-3e8b0b8a6c3b&pd_rd_wg=0I3Kz&pd_rd_i=B07VX3HQGJ&psc=1" rel="external">Pi Case</a>

_*These will be purchased ASAP*_
