### ISSUE TITLE
Develop python3 script for opening and closing the “lock” (7/26) 

### ISSUE THREAD

**Issue by NickHale1** [NickHale1/Deadbolt-Detector#21]

**Comment by nearybatwit** [comment]
Servo responds to degrees. Negative will engage the lock, positive will disengage

**Comment by nearybatwit** [comment]
The higher the angle, the more power the servo is given. Negative values also seems to have more power than positive.

**Comment by nearybatwit** [comment]
The workaround has been to set the lock engage signal to -5 degrees and the disengage to +15 degrees for 2 seconds each.

**Comment by nearybatwit** [comment]
Setting issue to closed for now -- any additions to the code will warrant a reopen to the issue and new comment.
