### ISSUE TITLE
Research best way to implement remote activation (7/26) 

### ISSUE THREAD

**Issue by NickHale1** [NickHale1/Deadbolt-Detector#22]

**Comment by nearybatwit** [comment]
https://www.digikey.com/en/maker/blogs/2021/how-to-control-servo-motors-with-a-raspberry-pi#:~:text=To%20make%20a%20Raspberry%20Pi,the%20power%20supply%20as%20well.

**Comment by nearybatwit** [comment]
Magpi will be used to remotely access the Raspberry Pi

**Comment by nearybatwit** [comment]
Research done, remote activation complete
